const excuses = [
    "I muss no zom Friseur",
    "I muss no dia Epfel fudd fiehra",
    "I sodd no Epfel klauba",
    "I dua no tanka",
    "I muss no mitm Hond naus",
    "I sodd no d'Oma hoim fiehra",
    "I benn doch scho en Nellanga",
    "I gang no pumba",
    "I komm noch zehne",
    "I muss no dr Chrischdbaum schmügga",
    "I komm en zehn Minuda",
    "I hau no a Teams-Meeting ghed",
    "I war no en dr Blaubeurer Stroß",
    "I hao koi persönlicha Eiladung kriegt",
    "I zock no midem Benheinz a Runde, dann komm I",
];
